# -*- coding: utf-8 -*-
"""build — inline the figure stylesheet into a course page.

Same discipline as the walkthrough and domain runtimes: generated output is
committed into the course, so a plain clone serves without this repo; you only
need it to rebuild. The block replaces itself, so a rebuild is idempotent.

Add `<!-- FIG:BUNDLE -->` once, in <head> or before </body>, then:

    python build.py --target course/index.html
    python build.py --target "output/*.html"
"""
from __future__ import annotations

import argparse
import glob as globmod
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSS = HERE / "figure.css"

PLACEHOLDER = "<!-- FIG:BUNDLE -->"
START, END = "<!-- FIG:START -->", "<!-- FIG:END -->"
EXCLUDE = ("scripts/dist", "node_modules", ".venv", "archive", "dist/")


def strip(src: str) -> str:
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return "\n".join(ln.strip() for ln in src.splitlines() if ln.strip())


def bundle() -> str:
    return (f"{START}\n<!-- generated by shared/figure/build.py — do not hand-edit -->\n"
            f"<style>{strip(CSS.read_text(encoding='utf-8'))}</style>\n{END}")


def inject(path: Path, block: str) -> None:
    src = path.read_text(encoding="utf-8")
    existing = re.search(re.escape(START) + r".*?" + re.escape(END), src, re.S)
    if existing:
        src = src[:existing.start()] + PLACEHOLDER + src[existing.end():]
    if PLACEHOLDER not in src:
        raise SystemExit(f"{path}: no {PLACEHOLDER} and no previously generated block — "
                         f"add the placeholder in <head> or before </body>")
    path.write_text(src.replace(PLACEHOLDER, block), encoding="utf-8")
    print(f"  {path}  (+{len(block.encode('utf-8')) / 1024:.1f} kB)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", action="append", required=True, help="glob(s), repeatable")
    args = ap.parse_args()

    targets: list[Path] = []
    for pattern in args.target:
        targets += [Path(h) for h in sorted(globmod.glob(pattern, recursive=True))
                    if Path(h).is_file() and not any(x in Path(h).as_posix() for x in EXCLUDE)]
    if not targets:
        raise SystemExit(f"no target matched {args.target}")

    block = bundle()
    print(f"embedding the figure vocabulary into {len(targets)} page(s):")
    for t in targets:
        inject(t, block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
